# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
name: "beats-winlogbeat"

env:
  GCP_DEFAULT_MACHINE_TYPE: "c2d-highcpu-8"
  GCP_HI_PERF_MACHINE_TYPE: "c2d-highcpu-16"
  GCP_WIN_MACHINE_TYPE: "n2-standard-8"

  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"
  IMAGE_WIN_10: "family/platform-ingest-beats-windows-10"
  IMAGE_WIN_11: "family/platform-ingest-beats-windows-11"
  IMAGE_WIN_2016: "family/platform-ingest-beats-windows-2016"
  IMAGE_WIN_2019: "family/platform-ingest-beats-windows-2019"
  IMAGE_WIN_2022: "family/platform-ingest-beats-windows-2022"

  IMAGE_BEATS_WITH_HOOKS_LATEST: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-beats-ci-with-hooks:latest"

  # Other deps
  ASDF_MAGE_VERSION: 1.15.0

  # Unit tests
  RACE_DETECTOR: "true"
  TEST_COVERAGE: "true"
  # See docker.go. Sets --pull to docker-compose
  DOCKER_PULL: 0

steps:
  - group: "Packaging"
    key: "winlogbeat-packaging"
    steps:
      - label: ":ubuntu: Winlogbeat: Packaging Linux"
        key: "packaging-linux"
        env:
          PLATFORMS: "+all linux/amd64 windows/amd64 darwin/amd64 darwin/arm64"
        command: |
          .buildkite/scripts/packaging/packaging.sh winlogbeat
        retry:
          automatic:
            - limit: 1
        timeout_in_minutes: 20
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
        notify:
          - github_commit_status:
              context: "winlogbeat: Packaging Linux"
