# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  AWS_ARM_INSTANCE_TYPE: "m6g.xlarge"
  AWS_IMAGE_UBUNTU_ARM_64: "platform-ingest-beats-ubuntu-2204-aarch64"

  GCP_DEFAULT_MACHINE_TYPE: "c2d-highcpu-8"
  GCP_HI_PERF_MACHINE_TYPE: "c2d-highcpu-16"
  GCP_WIN_MACHINE_TYPE: "n2-standard-8"

  IMAGE_MACOS_X86_64: "generic-13-ventura-x64"
  IMAGE_MACOS_ARM: "generic-13-ventura-arm"
  IMAGE_RHEL9: "family/platform-ingest-beats-rhel-9"
  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"
  IMAGE_WIN_10: "family/platform-ingest-beats-windows-10"
  IMAGE_WIN_11: "family/platform-ingest-beats-windows-11"
  IMAGE_WIN_2016: "family/platform-ingest-beats-windows-2016"
  IMAGE_WIN_2019: "family/platform-ingest-beats-windows-2019"
  IMAGE_WIN_2022: "family/platform-ingest-beats-windows-2022"

  IMAGE_BEATS_WITH_HOOKS_LATEST: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-beats-ci-with-hooks:latest"

  # Other deps
  ASDF_MAGE_VERSION: 1.15.0
  ASDF_NODEJS_VERSION: 18.17.1
  ASDF_PYTHON_VERSION: 3.10.9

  # Unit tests
  RACE_DETECTOR: "true"
  TEST_COVERAGE: "true"

  # Concurrency definition
  CONCURRENCY_GROUP: "orka-concurrency-group"
  CONCURRENCY_COUNT: 10
  CONCURRENCY_METHOD: eager

steps:
  - group: "Packaging"
    key: "heartbeat-packaging"

    steps:
      - label: ":ubuntu: Heartbeat: Packaging Linux"
        key: "heartbeat-package-linux"
        env:
          PLATFORMS: "+all linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64"
        command: |
          .buildkite/scripts/packaging/packaging.sh heartbeat
        retry:
          automatic:
            - limit: 1
        timeout_in_minutes: 20
        agents:
          provider: gcp
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
        notify:
          - github_commit_status:
              context: "heartbeat: Packaging Linux"

      - label: ":ubuntu: Heartbeat: Packaging Linux arm64"
        key: "heartbeat-package-linux-arm"
        env:
          PLATFORMS: "linux/arm64"
          PACKAGES: "docker"
        command: |
          .buildkite/scripts/packaging/packaging.sh heartbeat
        retry:
          automatic:
            - limit: 1
        timeout_in_minutes: 20
        agents:
          provider: "aws"
          imagePrefix: "${AWS_IMAGE_UBUNTU_ARM_64}"
          instanceType: "${AWS_ARM_INSTANCE_TYPE}"
        notify:
          - github_commit_status:
              context: "heartbeat: Packaging Linux arm64"
