name: create-matrix

inputs:
  os-versions:
    description: "Required OS versions to run tests on"
    required: true
  workflow-name:
    description: "Name of the current workflow"
    required: true
  pr-target-branch:
    description: "Target branch of current PR"
outputs:
  matrix:
    description: "Matrix with beats and OS versions"
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - name: Define Matrix
      run: ./.github/actions/test-matrix-composite-action/generate-matrix.sh ${{ inputs.os-versions }}
      shell: bash
      env:
        WORKFLOW_NAME: ${{ inputs.workflow-name }}


    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
