# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
name: "beats-xpack-dockerlogbeat"

env:
  AWS_ARM_INSTANCE_TYPE: "m6g.xlarge"
  AWS_IMAGE_UBUNTU_ARM_64: "platform-ingest-beats-ubuntu-2204-aarch64"

  GCP_DEFAULT_MACHINE_TYPE: "c2d-highcpu-8"
  GCP_HI_PERF_MACHINE_TYPE: "c2d-highcpu-16"

  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"

  IMAGE_BEATS_WITH_HOOKS_LATEST: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-beats-ci-with-hooks:latest"

  # Other deps
  ASDF_MAGE_VERSION: 1.15.0

  # Unit tests
  RACE_DETECTOR: "true"
  TEST_COVERAGE: "true"

steps:
  - group: "Packaging"
    key: "xpack-dockerlogbeat-packaging"

    steps:
      - label: ":ubuntu: x-pack/dockerlogbeat: Packaging Linux"
        key: "auditbeat-package-linux-x86"
        env:
          PLATFORMS: "+all linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64"
        command: |
          .buildkite/scripts/packaging/packaging.sh x-pack/dockerlogbeat
        retry:
          automatic:
            - limit: 1
        timeout_in_minutes: 20
        agents:
          provider: gcp
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
        notify:
          - github_commit_status:
              context: "x-pack/dockerlogbeat: Packaging Linux"

      - label: ":ubuntu: x-pack/dockerlogbeat: Packaging Linux arm64"
        key: "auditbeat-package-linux-arm"
        env:
          PLATFORMS: "linux/arm64"
          PACKAGES: "docker"
        command: |
          .buildkite/scripts/packaging/packaging.sh x-pack/dockerlogbeat
        retry:
          automatic:
            - limit: 1
        timeout_in_minutes: 20
        agents:
          provider: "aws"
          imagePrefix: "${AWS_IMAGE_UBUNTU_ARM_64}"
          instanceType: "${AWS_ARM_INSTANCE_TYPE}"
        notify:
          - github_commit_status:
              context: "x-pack/dockerlogbeat: Packaging Linux arm64"
