## NB! Name of the workflow should be same as a filename
name: macos-unit-tests-push

on:
## `pull_request` to be removed after the testing
  pull_request:
  push:
    branches:
      - main
    paths:
      - auditbeat
      - filebeat
      - heartbeat
      - metricbeat
      - packetbeat
      - x-pack/auditbeat
      - x-pack/filebeat
      - x-pack/heartbeat
      - x-pack/metricbeat
      - x-pack/osquerybeat
      - x-pack/packetbeat
      - .github/actions/test-matrix-composite-action
      - .github/workflows/macos-unit-tests-push.yml

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  matrix-prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.run-composite.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - name: "Define matrix"
        id: set-matrix
        uses: ./.github/actions/test-matrix-composite-action
        with:
          os-versions: macos-13 macos-14
          workflow-name: ${{ github.workflow }}

      - name: "Print out matrix"
        run:  echo ${{ steps.run-composite.outputs.matrix }}

  unit-tests:
    needs: matrix-prep
    if: ${{ needs.matrix-prep.outputs.matrix != '' }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix: ${{ fromJson(needs.matrix-prep.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version-file: .python-version

      - name: Install mage
        run: go install github.com/magefile/mage

      - name: Run build
        run: mage build
        working-directory: ${{ matrix.beat }}

      - name: Run unitTest
        run: mage unitTest
        working-directory: ${{ matrix.beat }}

  # TODO: centralise github job with the status.
