name: macos-unit-tests-pr

on:
  pull_request:

permissions:
  contents: read

# Available image list: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
env:
  MACOS_13_X64: macos-13
  MACOS_14_ARM: macos-14

# to configure for PRs then cancel them
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      #ToDo: add case when only macos-unit-tests-pr.yml is changed && when macos-unit-tests-pr.yml && some beat is changed
      - name: "Define matrix"
        id: set-matrix
        run: |
          changedDirs=$(git diff --dirstat=files HEAD~1 | sed 's/^[ 0-9.]\+% //g' | awk -F/ '{print $1}' | sort -u)
          relevantDirs=($(echo "$changedDirs" | grep -Fxf .github/workflows/macos.d/values.d/whitelisted-dirs))
          osArray=($MACOS_13_X64 $MACOS_14_ARM)

          matrix=$(jq -n --argjson dirs "$(printf '%s\n' "${relevantDirs[@]}" | jq -R . | jq -s .)" \
              --argjson osArray "$(printf '%s\n' "${osArray[@]}" | jq -R . | jq -s .)" \
              '[ $dirs[] as $dir | $osArray[] as $os | {beat: $dir, os: $os} ]')

          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT

  unit-tests:
    needs: matrix_prep
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version-file: .python-version

      - name: Install mage
        run: go install github.com/magefile/mage

      - name: Run build
        run: mage build
        working-directory: ${{ matrix.beat }}

      - name: Run unitTest
        run: mage unitTest
        working-directory: ${{ matrix.beat }}

  # TODO: centralise github job with the status.
