name: macos-unit-tests-pr

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

# Available image list: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
env:
  MACOS_13_X64: macos-13
  MACOS_14_ARM: macos-14

# to configure for PRs then cancel them
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  matrix-prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - name: "Define matrix"
        id: set-matrix
        run: |
          .github/workflows/macos.d/generate-matrix.sh

  unit-tests:
    needs: matrix-prep
    if: ${{ needs.matrix-prep.outputs.matrix != '' }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix: ${{ fromJson(needs.matrix-prep.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version-file: .python-version

      - name: Install mage
        run: go install github.com/magefile/mage

      - name: Run build
        run: mage build
        working-directory: ${{ matrix.beat }}

      - name: Run unitTest
        run: mage unitTest
        working-directory: ${{ matrix.beat }}

  # TODO: centralise github job with the status.
